package com.hicham.backend.model;

public enum ProgressType {
    GENERATION_STARTED,
    GENERATION_PROGRESS,
    GENERATION_COMPLETED,
    GENERATION_ERROR,
    VALIDATION_PROGRESS,
    DEPLOYMENT_PROGRESS
} 